---
date: 2020-07-05
model:
- class: Server
  key: serialnumber
  fields:
  - label: 名称
    value:
      axis: A
  - label: 组织->名称
    value:
      axis: =Demo
  - label: 状态
    value:
      axis: C
      filter:
      - replace(00=在线,01=已下线)
  - label: 机柜->全称
    value:
      axis: F
      filter:
      - join(E,F)
  - label: 投产日期
    value:
      axis: G
      filter:
      - date()
      